### ISSUE TITLE
Entität Partner

### ISSUE THREAD

**Issue by cedrickf** [fom-pm-se/backend#34]
Es soll eine Entität Partner angelegt werden. Diese Entität kann ein Zulieferer, ein Kunde, oder ein sonstiger Geschäftspartner sein.
Ein Partner hat einen Namen, eine Adresse, mindestens eine Telefonnummer, einen Typ (Kunde, Zulieferer, sonstiger Geschäftspartner) und ein Bild/Favicon. 
Partner können über einen Dialog im FE angelegt oder bearbeitet werden.

**Comment by leonschbbht** [comment]
Die Partner-Entität steht entsprechend der Anforderungen.
Die Funktion dem Partner ein Bild oder Favicon zuzuordnen würde ich in einem späteren PR ergänzen, da ich hierzu gerne das Frontend in erster Funktion umsetzen würde --> #36
