### ISSUE TITLE
Notizfeld Partnerseite

### ISSUE THREAD

**Issue by cedrickf** [fom-pm-se/backend#35]
### Userstory
Als MA möchte ich eine Funktion haben, die es mir ermöglicht Notizen zu einem Partner hinzuzufügen, damit ich Informationen gezielt abspeichern kann.

### Akzeptanzkriterien

- [x] Notizen Entität ist angelegt, die ein `auditable` implementiert damit Meta-Informationen zum Ersteller und Zeitstempeln automatisch ermittelt werden.
- [x] Notizen Entität enthält folgende zusätzliche Attribute: `id`, `text`
- [x] POST-Endpunkt ist unter `/api/v1/partner/{id}/notes` angelegt, der es ermöglicht eine Notiz zu einem bestehenden Partner anzulegen
- [x] PUT-Endpunkt ist unter `/api/v1/partner/{id}/notes/{id}` angelegt, der es ermöglicht eine bestehende Notiz zu aktualisieren und automatisch zu speichern
- [x] DELETE-Endpunkt ist unter `/api/v1/partner/{id}/notes/{id}` angelegt der es ermöglicht eine bestehende Notiz zu löschen

**Comment by leonschbbht** [comment]
Klingt für mich eher nach einem Frontend-Task.
Hier geht es vermutlich um die Backend-Funktionalität, dass einem Partner eine Notiz als Text zugeordnet wird, oder?
Soll es mehrere Notizen pro Partner geben können?

**Comment by cedrickf** [comment]
Ja genau darum geht es hierbei. Für das FE gibt es noch ein eigenes Issue. Ein Partner soll im FE ein Notizfeld haben in dem alle Notizen (ggf. Gefiltert) eingezeigt werden. Eine Umsetzung mit n Notizen die individuell gespeichert werden ist vermutlich am sinnvollsten. Eine Notiz hätte dann ein Datetime, Author und einen Text.

**Comment by leonschbbht** [comment]
> Ja genau darum geht es hierbei. Für das FE gibt es noch ein eigenes Issue. Ein Partner soll im FE ein Notizfeld haben in dem alle Notizen (ggf. Gefiltert) eingezeigt werden. Eine Umsetzung mit n Notizen die individuell gespeichert werden ist vermutlich am sinnvollsten. Eine Notiz hätte dann ein Datetime, Author und einen Text.

Ich habe Anpassung an den Anforderungen vorgenommen, damit der Backend-Task besser vom Frontend-Task abgegrenzt werden kann. Das automatische speichern ist eine Funktion die wir im Frontend abbilden, da wir sonst eine WebSocket Connection implementieren müssten. Das wäre ein unverhältnismäßiger Aufwand.

**Comment by leonschbbht** [comment]
Habe es so implementiert, dass die ID's nicht teil der URL sind sondern des Request Bodys, macht den Umgang mit der Schnittstelle im Frontend etwas leichter.
